---
title: "TEMPOmap_nc_ratio"
author: "Haowen Zhou"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup 

```{r load_package&data}
suppressMessages(require(Seurat))
suppressMessages(require(SeuratDisk))
suppressMessages(require(raster))
suppressMessages(require(stringr))
suppressMessages(require(dplyr))
suppressMessages(require(parallel))
suppressMessages(require(pbapply))
suppressMessages(require(ggplot2))
suppressMessages(require(readr))
suppressMessages(require(ggpubr))
suppressMessages(require(monocle3))
suppressMessages(library(nleqslv))
suppressMessages(library(magrittr))
suppressMessages(library(circlize))
suppressMessages(library(RColorBrewer))
suppressMessages(library(ComplexHeatmap))

setwd("~/Desktop/At_Broad/Subcellular")
#Convert Data
#Convert("2021-09-24-Rena-EU-starmap-raw-KD-combined.h5ad", dest = "h5seurat", overwrite = TRUE)
#Convert("2021-09-24-Rena-EU-starmap-cc.h5ad", dest = "h5seurat", overwrite = TRUE)
#Convert("2022-02-04-Rena-EU-starmap-after-pp-300.h5ad", dest = "h5seurat", overwrite = TRUE)
#Load Data
starmap <- LoadH5Seurat("2021-09-24-Rena-EU-starmap-raw-KD-combined.h5seurat")
```

## Function Defination

```{r func_def}
sc_fitting <- function(gene_list,psd_bulk_list, v_n, v_c){
  for(i in names(psd_bulk_list)){
    psd_bulk_list[[i]] %<>% subset(subset = `1h_labeling` > 0 & 
                                     `1h_labeling_1h_wash` > 0 & 
                                     `1h_labeling_2h_wash` > 0 & 
                                     `1h_labeling_4h_wash` > 0 & 
                                     `1h_labeling_6h_wash` > 0 )
    gene_list %<>% intersect(psd_bulk_list[[i]]$gene)
  }
  
  for(i in names(psd_bulk_list)){
    psd_bulk_list[[i]] %<>% subset(subset = gene %in% gene_list)
  }
  time_vec <- c(2,4,6)
  
  beta_list <- apply(data.frame(gene = gene_list),1,
                FUN = function(x){
                  time_vec2 <- c(0,time_vec)
                  expr_vec <- rep(0,4)
                  for(i in 1:length(time_vec)){
                    expr_vec[i+1] <- log(psd_bulk_list$RNA[["1h_labeling"]][psd_bulk_list$RNA$gene == x[["gene"]]]) -
                      log(psd_bulk_list$RNA[[paste("1h_labeling_",
                                                     time_vec[i],"h_wash",
                                                     sep = "")]][psd_bulk_list$RNA$gene == x[["gene"]]])
                  }
                  lm_res <- lm(expr~time,data.frame(time = time_vec2, expr = expr_vec))
                  return(list(gene = x[["gene"]],
                              beta = lm_res[["coefficients"]][["time"]],
                              beta_r_sq = summary(lm_res)[["r.squared"]], 
                              beta_adj_r_sq = summary(lm_res)[["adj.r.squared"]],
                              beta_expr_vec = log(psd_bulk_list$RNA[["1h_labeling"]][psd_bulk_list$RNA$gene == x[["gene"]]]) - expr_vec))
                  })
  label_para_df <- do.call(rbind,beta_list) %>% as.data.frame()
  for(i in colnames(label_para_df)[1:4]) label_para_df[[i]] <- unlist(label_para_df[[i]])

  label_para_df[["alpha"]] <- apply(label_para_df,1,
                                    FUN = function(x){
                                      if(is.na(x[["beta"]]) | as.numeric(x[["beta"]]) < 0){
                                        NA
                                      }else{
                                        as.numeric(x[["beta"]]) * psd_bulk_list$RNA$`1h_labeling`[psd_bulk_list$RNA$gene == x[["gene"]]]/
                                          (1 - exp(-1 * as.numeric(x[["beta"]])))
                                      }
                                    })

  ked_list <- apply(data.frame(gene = gene_list),1,
                            FUN = function(x){
                              time_vec2 <- c(0,time_vec)
                              expr_vec <- rep(0,4)
                              for(i in 1:length(time_vec)){
                                expr_vec[i+1] <- log(psd_bulk_list$Nucleus[["1h_labeling"]][psd_bulk_list$Nucleus$gene == x[["gene"]]]) -
                                log(psd_bulk_list$Nucleus[[paste("1h_labeling_",
                                                     time_vec[i],"h_wash",
                                                     sep = "")]][psd_bulk_list$Nucleus$gene == x[["gene"]]])
                              }
                              lm_res <- lm(expr~time,data.frame(time = time_vec2, expr = expr_vec))
                              return(list(gene = x[["gene"]],
                                ked = lm_res[["coefficients"]][["time"]],
                                ked_r_sq = summary(lm_res)[["r.squared"]], 
                                ked_adj_r_sq = summary(lm_res)[["adj.r.squared"]],
                                ked_expr_vec = log(psd_bulk_list$Nucleus[["1h_labeling"]][psd_bulk_list$Nucleus$gene == x[["gene"]]]) - expr_vec))
                            })
  
  wash_para_df <- do.call(rbind,ked_list) %>% as.data.frame()
  for(i in colnames(wash_para_df)[1:4]) wash_para_df[[i]] <- unlist(wash_para_df[[i]])
  
  tmp_df <- data.frame(label_para_df[,1:6],wash_para_df[,2:5])
  #Use 20h get beta_c/lambda
  tmp_df[["beta_c_lambda_ratio"]] <- apply(tmp_df,1,
                                           FUN = function(x){
                                             if(psd_bulk_list$Nucleus[["20h_labeling"]][psd_bulk_list$Nucleus$gene == x[["gene"]]] == 0 | psd_bulk_list$Cytoplasm[["20h_labeling"]][psd_bulk_list$Cytoplasm$gene == x[["gene"]]] == 0) NA
                                             else{
                                               psd_bulk_list$Nucleus[["20h_labeling"]][psd_bulk_list$Nucleus$gene == x[["gene"]]] * v_n[["20h_labeling"]] / (v_c[["20h_labeling"]] * psd_bulk_list$Cytoplasm[["20h_labeling"]][psd_bulk_list$Cytoplasm$gene == x[["gene"]]])
                                             }
                                             
                                           })
  ##Using LSS
  tmp_list <- apply(tmp_df, 1, 
                    FUN = function(x){
                      if(is.na(x[["beta"]]) | as.numeric(x[["ked"]]) < 0 | is.infinite(as.numeric(x[["ked"]])) | is.na(x[["beta_c_lambda_ratio"]])){
                          NA
                      }else{
                        n_index = psd_bulk_list$Nucleus$gene == x[["gene"]]
                        c_index = psd_bulk_list$Cytoplasm$gene == x[["gene"]]
                        r_index = psd_bulk_list$RNA$gene == x[["gene"]]
                        
                        n0 <- rep(psd_bulk_list$Nucleus$`1h_labeling`[n_index],length(time_vec)+1)
                        ked <- rep(as.numeric(x[["ked"]]),  length(time_vec)+1)
                        b <- rep(as.numeric(x[["beta"]]),   length(time_vec)+1)
                        k <- rep(x[["beta_c_lambda_ratio"]],length(time_vec)+1)
                        c_vec = rep(0,length(time_vec)+1)
                        x_vec = rep(0,length(time_vec)+1)
                        n_vec = rep(0,length(time_vec)+1)
                        
                        c_r_vec = rep(0,length(time_vec)+1)
                        x_r_vec = rep(0,length(time_vec)+1)
                        n_r_vec = rep(0,length(time_vec)+1)
                        
                        t_vec = c(0,time_vec)
                        vc = rep(0,length(time_vec)+1)
                        vn = rep(0,length(time_vec)+1)
                        
                        #lh labeling
                        c_vec[1] =  psd_bulk_list$Cytoplasm$`1h_labeling`[c_index]
                        n_vec[1] =  psd_bulk_list$Nucleus$`1h_labeling`[n_index]
                        x_vec[1] =  psd_bulk_list$RNA$`1h_labeling`[r_index]
                        
                        c_r_vec[1] =  psd_bulk_list$Cytoplasm_r$`1h_labeling`[c_index]
                        n_r_vec[1] =  psd_bulk_list$Nucleus_r$`1h_labeling`[n_index]
                        x_r_vec[1] =  psd_bulk_list$RNA_r$`1h_labeling`[r_index]
                        vc[1] = v_c[["1h_labeling"]]
                        vn[1] = v_n[["1h_labeling"]]
                        
                        for(i in 1:length(time_vec)){
                          c_vec[i+1] = psd_bulk_list$Cytoplasm[[paste0("1h_labeling_",time_vec[i],"h_wash")]][c_index]
                          n_vec[i+1] = psd_bulk_list$Nucleus[[paste0("1h_labeling_",time_vec[i],"h_wash")]][n_index]
                          x_vec[i+1] = psd_bulk_list$RNA[[paste0("1h_labeling_",time_vec[i],"h_wash")]][r_index]
                          c_r_vec[i+1] = psd_bulk_list$Cytoplasm_r[[paste0("1h_labeling_",time_vec[i],"h_wash")]][c_index]
                          n_r_vec[i+1] = psd_bulk_list$Nucleus_r[[paste0("1h_labeling_",time_vec[i],"h_wash")]][n_index]
                          x_r_vec[i+1] = psd_bulk_list$RNA_r[[paste0("1h_labeling_",time_vec[i],"h_wash")]][r_index]
                          vc[i+1] = v_c[[paste0("1h_labeling_",time_vec[i],"h_wash")]]
                          vn[i+1] = v_n[[paste0("1h_labeling_",time_vec[i],"h_wash")]]
                        }

                        tmp_obj <- suppressWarnings(tryCatch({
                            nls(c_vec~x*exp(- beta_c * t_vec) - lambda * n0 * vn/(vc * (ked - beta_c)) * exp(-ked * t_vec),
                                start = list(x = 0.1, beta_c = 0.1, lambda = 0.1))
                            #nls(c_vec~x*exp(- beta_c * t_vec) - (ked + beta_c * c_r_vec/n_r_vec - x_r_vec/n_r_vec * b) * n0 * vn/(vc * (ked - beta_c)) * exp(-ked * t_vec),
                                #start = list(x = 0.1, beta_c = k[1]*ked[1]/2))
                        },
                        error = function(x){return(NA) }))
                        
                        tmp_list <- list()
                        if(!sum(is.na(tmp_obj))){
                          tmp_list[["lambda"]] = coef(tmp_obj)[["lambda"]]
                          tmp_list[["beta_c"]] = coef(tmp_obj)[["beta_c"]]
                        }else {tmp_list[["lambda"]]=NA;tmp_list[["beta_c"]] =NA}
                        
                        return(tmp_list)
                        }
                    })
  
  tmp_df2 <- do.call(rbind,tmp_list) %>% as.data.frame()
  tmp_df[["lambda"]] <- as.numeric(tmp_df2$lambda)
  #tmp_df[["lambda2"]] <- as.numeric(tmp_df2$lambda2)
  tmp_df[["beta_c"]] <- as.numeric(tmp_df2$beta_c)
  #tmp_df[["beta_c2"]] <- as.numeric(tmp_df2$beta_c2)
  tmp_df[["beta_n"]] <- apply(tmp_df,1,
                      FUN = function(x){
                        ked <- as.numeric(x[["ked"]]); ke <- as.numeric(x[["lambda"]])
                        ked - ke
                      })
  #tmp_df[["lambda_vec"]] <- tmp_df2$lambda_vec
  #res_df <- subset(tmp_df, !is.na(kdn) & kdn > 0 & kdc > 0 & ke > 0 )
  res_df <- subset(tmp_df, !is.na(alpha) & alpha > 0)
}

get_psd_bulk <- function(cc_stage = NULL, kd_label = NULL, seurat.obj){
  psd_bulk_list <- list(RNA = data.frame(gene = row.names(starmap_normalized)),
                        Cytoplasm = data.frame(gene = row.names(starmap_normalized)),
                        Nucleus = data.frame(gene = row.names(starmap_normalized)))
  
  for(i in levels(starmap_normalized@meta.data$sample)){
    tmp_vec <- starmap_normalized@meta.data$sample == i 
    if(!is.null(cc_stage)) tmp_vec & starmap_normalized@meta.data$Phase == cc_stage
    if(!is.null(kd_label)) tmp_vec & starmap_normalized@meta.data$KD_label_combined == kd_label
    psd_bulk_list$RNA[[i]] <- rowSums(starmap_normalized@assays$RNA@counts[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$Cytoplasm[[i]] <- rowSums(starmap_normalized@assays$cytoplasm@data[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$Nucleus[[i]] <- rowSums(starmap_normalized@assays$nucleus@data[,tmp_vec])/sum(tmp_vec)
  }
}

get_density <- function(x, y, ...) {
  suppressMessages(library(MASS))
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
```

## Calc. Volumes

```{r}
#read image
library(terra)
library(raster)


img_list <- paste0("img/",list.files("img"))
img_summ_list <- list()
for(i in img_list){
  tmp_img <- sds(i)
  tmp_list <- list()
  message(paste(i,", Layers:", length(names(tmp_img))))
  for(j in 1:length(names(tmp_img))){
    suppressMessages(tmp_list[[j]] <- freq(tmp_img[j]))
  }
  img_summ_list[[i]] <- tmp_list
}

img_summ_list <- readRDS("~/Desktop/At_Broad/Subcellular/img_summ_ls.RDS")
starmap@meta.data[["n_volume"]] <- 0

for(i in c("1h_labeling_1h_wash","1h_labeling_2h_wash","1h_labeling_4h_wash","1h_labeling_6h_wash","1h_labeling","20h_labeling")){
  message(paste("Sample:", i))
  for(j in img_summ_list[[paste0("img/",i,".tif")]]){
    starmap@meta.data$n_volume <- apply(starmap@meta.data,1,
                                        FUN = function(x){
                                          if(x[["sample"]] == i & 
                                             (as.numeric(x[["orig_index"]])+1) %in% j[,"value"]){#orig_index + 1
                                            as.numeric(x[["n_volume"]]) + 
                                              j[,"count"][j[,"value"] == (as.numeric(x[["orig_index"]])+1)]
                                            }else as.numeric(x[["n_volume"]])
                                        })
  }
  
}


```

## Sample-wise normalization

```{r}
#Normalize by ctrl genes 
starmap_normalized <- starmap
normalize_list <- list(RNA = rep(0,6))
names(normalize_list[["RNA"]]) <- levels(starmap@meta.data$sample)

for(i in levels(starmap@meta.data$sample)){
  normalize_list[["RNA"]][i] <- mean(colSums(starmap@assays$RNA@counts[c(1:2,4:7),starmap@meta.data$sample == i]))
  normalize_list[["RNA"]][i] <- normalize_list[["RNA"]][i]/mean(colSums(starmap@assays$RNA@counts[c(1:2,4:7),starmap@meta.data$sample == "1h_labeling"]))
}

for(i in levels(starmap@meta.data$sample)){
  starmap_normalized@assays$RNA@counts[,starmap@meta.data$sample == i] <- 
    starmap@assays$RNA@counts[,starmap@meta.data$sample == i]/normalize_list[["RNA"]][i]
  starmap_normalized@assays$nucleus@data[,starmap@meta.data$sample == i] <- 
    starmap@assays$nucleus@data[,starmap@meta.data$sample == i]/normalize_list[["RNA"]][i]
  starmap_normalized@assays$cytoplasm@data[,starmap@meta.data$sample == i] <- 
    starmap@assays$cytoplasm@data[,starmap@meta.data$sample == i]/normalize_list[["RNA"]][i]
}

#Normalize by volume
#Using External cc label
cc_df <- read_csv("~/Desktop/At_Broad/Subcellular/2021-10-06-obs.csv")
starmap_normalized@meta.data[["Phase"]] <- cc_df$phase_ref
#divided by volume
starmap_raw_norm <- starmap_normalized
tmp_mat <- matrix(rep(starmap_normalized@meta.data$volume/100000,each = dim(starmap_normalized@assays$RNA@counts)[1]), byrow = F,
                  nrow = dim(starmap_normalized@assays$RNA@counts)[1])
starmap_normalized@assays$RNA@counts <- starmap_normalized@assays$RNA@counts / tmp_mat

tmp_mat <- matrix(rep(starmap_normalized@meta.data$n_volume/100000,each = dim(starmap_normalized@assays$nucleus@data)[1]), byrow = F,
                  nrow = dim(starmap_normalized@assays$nucleus@data)[1])
starmap_normalized@assays$nucleus@data <- starmap_normalized@assays$nucleus@data / tmp_mat

tmp_mat <- matrix(rep((starmap_normalized@meta.data$volume-starmap_normalized@meta.data$n_volume)/100000,each = dim(starmap_normalized@assays$cytoplasm@data)[1]), byrow = F,
                  nrow = dim(starmap_normalized@assays$cytoplasm@data)[1])
starmap_normalized@assays$cytoplasm@data <- starmap_normalized@assays$cytoplasm@data / tmp_mat

rm(tmp_mat)
#Remove genes
gene_list <- row.names(starmap_normalized@assays$RNA@counts)
gene_list <- gene_list[!gene_list %in% c("METTL14","METTL3","YTHDC1","YTHDC2","YTHDF1","YTHDF2","YTHDF3")]

```

##Parameters fitting

```{r get result}
#para fitting + nc wrapper
#Assign new label
tmp_vec <- starmap_normalized@assays[["RNA"]]@data[3,starmap_normalized@meta.data$sample!="20h_labeling"]/colSums(starmap_normalized@assays[["RNA"]]@data[c(1,2,4:7),starmap_normalized@meta.data$sample!="20h_labeling"])
tmp_vec <- starmap_normalized@assays[["RNA"]]@data[3,]/colSums(starmap_normalized@assays[["RNA"]]@data[c(1,2,4:7),])

starmap_normalized@meta.data$KD_label_new <- 
  sapply(tmp_vec,
         FUN = function(x){
           #quantile(tmp_vec)#no 20h
           #      10%       90% 
           #0.0754717 0.4318182
           #
           #0.1250000 0.3191489
           if(as.numeric(x) >= 0.3191489 )
             "siControl"
           
           else if(as.numeric(x) <= 0.125)
             "siYTHDC1"
           else "middle"
             })
starmap_raw_norm@meta.data$KD_label_new <- starmap_normalized@meta.data$KD_label_new

ggplot(data = data.frame(label = starmap_normalized@meta.data$KD_label_new,
                         YTHDC1 = tmp_vec) %>% subset(subset = label != "middle"), 
       aes(x = label, y = log2(1+YTHDC1), fill = label))+
  ylim(0,quantile(tmp_vec,probs = 0.99))+
  #geom_violin(alpha = 0.5) +
  geom_boxplot(width=0.1, color = "black", notch = T) + 
  theme_classic()


res_list <- list()

for(i in c("G1","S","G2M")){
  for(k in c("siControl","siYTHDC1")){
    psd_bulk_list <- list(RNA = data.frame(gene = row.names(starmap_normalized)),
                    Cytoplasm = data.frame(gene = row.names(starmap_normalized)),
                    Nucleus = data.frame(gene = row.names(starmap_normalized)),
                    RNA_r = data.frame(gene = row.names(starmap_normalized)),
                    Cytoplasm_r = data.frame(gene = row.names(starmap_normalized)),
                    Nucleus_r = data.frame(gene = row.names(starmap_normalized)))
    v_n <- c()
    v_c <- c()
    for(j in levels(starmap_normalized@meta.data$sample)){
      tmp_vec <- starmap_normalized@meta.data$sample == j & 
        starmap_normalized@meta.data$Phase == i & 
        starmap_normalized@meta.data$KD_label_new == k
      v_n <- setNames(c(v_n,mean(starmap_normalized@meta.data$n_volume[tmp_vec])),c(names(v_n),j))
      v_c <- setNames(c(v_c,mean(starmap_normalized@meta.data$volume[tmp_vec])-mean(starmap_normalized@meta.data$n_volume[tmp_vec])),
                    c(names(v_c),j))
      psd_bulk_list$RNA[[j]] <- rowSums(starmap_normalized@assays$RNA@counts[,tmp_vec])/sum(tmp_vec)
      psd_bulk_list$Cytoplasm[[j]] <- rowSums(starmap_normalized@assays$cytoplasm@data[,tmp_vec])/sum(tmp_vec)
      psd_bulk_list$Nucleus[[j]] <- rowSums(starmap_normalized@assays$nucleus@data[,tmp_vec])/sum(tmp_vec)
      psd_bulk_list$RNA_r[[j]] <- rowSums(starmap_raw_norm@assays$RNA@counts[,tmp_vec])/sum(tmp_vec)
      psd_bulk_list$Cytoplasm_r[[j]] <- rowSums(starmap_raw_norm@assays$cytoplasm@data[,tmp_vec])/sum(tmp_vec)
      psd_bulk_list$Nucleus_r[[j]] <- rowSums(starmap_raw_norm@assays$nucleus@data[,tmp_vec])/sum(tmp_vec)
    }
    res_df <- sc_fitting(gene_list,psd_bulk_list,v_n/100000,v_c/100000)
    for(j in levels(starmap_raw_norm@meta.data$sample)){
      tmp_vec <- starmap_normalized@meta.data$sample == j & 
        starmap_raw_norm@meta.data$Phase == i & 
        starmap_raw_norm@meta.data$KD_label_new == k
      res_df[[paste0(j,"_nc")]] <- apply(res_df,1,
                                         FUN = function(x){
                                           sum(starmap_raw_norm@assays$nucleus@data[x[["gene"]], tmp_vec]) /
                                              sum(starmap_raw_norm@assays$cytoplasm@data[x[["gene"]], tmp_vec] +
                                                 starmap_raw_norm@assays$nucleus@data[x[["gene"]], tmp_vec])
                                         })

    }
    tmp_list  <- apply(res_df,1,
                       FUN = function(x){
                         sample_vec <- c("1h_labeling", "1h_labeling_2h_wash", 
                                         "1h_labeling_4h_wash", "1h_labeling_6h_wash")
                         time_vec <- c(0,2,4,6)
                         nc_vec <- rep(0,4)
                         for(h in 1:4){
                           nc_vec[h] <- as.numeric(x[[paste0(sample_vec[h],"_nc")]])
                         }
                         lm_res <- lm(nc~time, data.frame(nc = nc_vec, time = time_vec))
                         return(list(nc_ratio = lm_res[["coefficients"]][["time"]],
                                     nc_r_sq = summary(lm_res)[["r.squared"]], 
                                     nc_adj_r_sq = summary(lm_res)[["adj.r.squared"]]))
                         })
    tmp_df <- do.call(rbind, tmp_list)
    res_df[["nc_slope"]] <- -1 * as.numeric(tmp_df[,"nc_ratio"])
    res_df[["nc_r_sq"]] <- as.numeric(tmp_df[,"nc_r_sq"])
    res_df[["nc_adj_r_sq"]] <- as.numeric(tmp_df[,"nc_adj_r_sq"])
    res_list[[paste(k,i,sep = "_")]] <- res_df
  }
}


for(k in c("siControl","siYTHDC1")){
  psd_bulk_list <- list(RNA = data.frame(gene = row.names(starmap_normalized)),
                    Cytoplasm = data.frame(gene = row.names(starmap_normalized)),
                    Nucleus = data.frame(gene = row.names(starmap_normalized)),
                    RNA_r = data.frame(gene = row.names(starmap_normalized)),
                    Cytoplasm_r = data.frame(gene = row.names(starmap_normalized)),
                    Nucleus_r = data.frame(gene = row.names(starmap_normalized)))
  v_n <- c()
  v_c <- c()
  for(j in levels(starmap_normalized@meta.data$sample)){
    tmp_vec <- starmap_normalized@meta.data$sample == j & 
      starmap_normalized@meta.data$KD_label_new == k
    v_n <- setNames(c(v_n,mean(starmap_normalized@meta.data$n_volume[tmp_vec])),c(names(v_n),j))
    v_c <- setNames(c(v_c,mean(starmap_normalized@meta.data$volume[tmp_vec])-mean(starmap_normalized@meta.data$n_volume[tmp_vec])),
                    c(names(v_c),j))
    psd_bulk_list$RNA[[j]] <- rowSums(starmap_normalized@assays$RNA@counts[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$Cytoplasm[[j]] <- rowSums(starmap_normalized@assays$cytoplasm@data[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$Nucleus[[j]] <- rowSums(starmap_normalized@assays$nucleus@data[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$RNA_r[[j]] <- rowSums(starmap_raw_norm@assays$RNA@counts[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$Cytoplasm_r[[j]] <- rowSums(starmap_raw_norm@assays$cytoplasm@data[,tmp_vec])/sum(tmp_vec)
    psd_bulk_list$Nucleus_r[[j]] <- rowSums(starmap_raw_norm@assays$nucleus@data[,tmp_vec])/sum(tmp_vec)
  }
  res_df <- sc_fitting(gene_list,psd_bulk_list,v_n/100000,v_c/100000)
  for(j in levels(starmap_raw_norm@meta.data$sample)){
      tmp_vec <- starmap_raw_norm@meta.data$sample == j & 
        starmap_raw_norm@meta.data$KD_label_new == k
      res_df[[paste0(j,"_nc")]] <- apply(res_df,1,
                                         FUN = function(x){
                                           sum(starmap_raw_norm@assays$nucleus@data[x[["gene"]], tmp_vec]) /
                                              sum(starmap_raw_norm@assays$cytoplasm@data[x[["gene"]], tmp_vec] +
                                                 starmap_raw_norm@assays$nucleus@data[x[["gene"]], tmp_vec])
                                         })


    }
    tmp_list  <- apply(res_df,1,
                       FUN = function(x){
                         sample_vec <- c("1h_labeling", "1h_labeling_2h_wash", 
                                         "1h_labeling_4h_wash", "1h_labeling_6h_wash")
                         time_vec <- c(0,2,4,6)
                         nc_vec <- rep(0,4)
                         for(h in 1:4){
                           nc_vec[h] <- as.numeric(x[[paste0(sample_vec[h],"_nc")]])
                         }
                         lm_res <- lm(nc~time, data.frame(nc = nc_vec, time = time_vec))
                         return(list(nc_ratio = lm_res[["coefficients"]][["time"]],
                                     nc_r_sq = summary(lm_res)[["r.squared"]], 
                                     nc_adj_r_sq = summary(lm_res)[["adj.r.squared"]]))
                         })
    tmp_df <- do.call(rbind, tmp_list)
    res_df[["nc_slope"]] <- -1 * as.numeric(tmp_df[,"nc_ratio"])
    res_df[["nc_r_sq"]] <- as.numeric(tmp_df[,"nc_r_sq"])
    res_df[["nc_adj_r_sq"]] <- as.numeric(tmp_df[,"nc_adj_r_sq"])
  res_list[[k]] <- res_df
}



```

```{r show slope r-sq}
res_df <- res_list$siControl

ggplot(res_df,aes(x = nc_r_sq))+
  geom_density() + 
  theme_classic()

ggplot(res_df[,c(1,20,22,24,26)] %>% melt(id.vars = "gene") %>% 
         group_by(variable) %>% summarise(avg_drop = mean(value)) ,aes(x = variable, y = avg_drop, fill = variable))+
    geom_bar(stat = "identity") + 
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))


res_df <- rbind(data.frame(Phase = "G1",res_list$siControl_G1),
                data.frame(Phase = "S",res_list$siControl_S),
                data.frame(Phase = "G2M",res_list$siControl_G2M))

ggplot(res_df,aes(x = nc_r_sq, color = Phase))+
  geom_density() + 
  theme_classic()

ggplot(res_df[,c(1,2,21,23,25,27)] %>% melt(id.vars = c("gene","Phase")) %>% 
         group_by(Phase,variable) %>% summarise(avg_drop = mean(value)) ,aes(x = variable, y = avg_drop, fill = Phase))+
    geom_bar(position="dodge", stat = "identity") + 
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

```



##Plot Para. Cor.

```{r plot corr}
require(viridis)

TEMPO_regression <- read_csv("~/Desktop/At_Broad/Subcellular/TEMPO-regression_siControl_new.csv")
#ctrl & regression
tmp_df <- left_join(res_list$siControl,TEMPO_regression, by = "gene")
colnames(tmp_df)[which(colnames(tmp_df) == "slope")] <- "gamma"
tmp_vec <- c("alpha","beta","nc_slope","gamma")

tmp_df %<>% subset(subset = beta_r_sq >= 0.5)

#tmp_df$beta_c <- tmp_df$beta_c2

plot_list <- list()
label_list <- c()


for(i in tmp_vec){
  for(j in tmp_vec){
    if(i == j){
      plot_list[[paste(i,j,sep = "_")]] <- 
        ggplot(data = tmp_df,aes_string(x = i))+ 
          geom_histogram(color="black", fill="white")+
          theme_classic()+
          xlim(ifelse(i %in% c("nc_slope","gamma"),quantile(tmp_df[[i]],probs = 0.01),0),
               quantile(tmp_df[[i]],probs = 0.99)) +
          theme(axis.title.x = element_blank(), axis.title.y = element_blank())
          #theme_void()+theme(panel.border = element_rect(colour = "black", fill=NA, size=1))
      label_list %<>% append(values = i)
    } else{
      plot_list[[paste(i,j,sep = "_")]] <-
        ggplot(data = tmp_df,
               aes_string(x = j,y = i, color = get_density(n = 100, x = tmp_df[[j]], y = tmp_df[[i]])))+ 
          geom_point(size = 0.5) +
          geom_smooth(data = tmp_df, mapping = aes_string(x = j,y = i), method=lm, se=FALSE, fullrange=TRUE, color = "red") +
          xlim(ifelse(j %in% c("nc_slope","gamma"),quantile(tmp_df[[j]],probs = 0.01),0),
               quantile(tmp_df[[j]],probs = 0.99)) +
          ylim(ifelse(i %in% c("nc_slope","gamma"),quantile(tmp_df[[i]],probs = 0.01),0),
               quantile(tmp_df[[i]],probs = 0.99)) +
          theme_classic() + scale_color_gradient(low = "#BDDBFF", high = "#1CAAF7") +
          theme(axis.title.x = element_blank(), axis.title.y = element_blank(),legend.position = "none")
          #theme_void()+theme(panel.border = element_rect(colour = "black", fill=NA, size=1),legend.position = "none")
      label_list %<>% append(values = cor(tmp_df[[j]],tmp_df[[i]], method = "pearson")^2 %>% formatC(format = "e", digits = 1))
      
    } 
        
  }
}

ggarrange(plotlist = plot_list,ncol = length(tmp_vec),nrow = length(tmp_vec), labels = label_list, label.x = 0.5)


```

##Cumulative Curve

```{r ctrl vs YTHDC1}
DC1_target <- read_csv("~/Desktop/At_Broad/Subcellular/DCtarget_label_new.csv") %>% .[,1:2]
tmp_df <- data.frame(gene = gene_list, Label_p = "na", Label = "na")
tmp_df[["Label_p"]] <- apply(tmp_df,1,
                              FUN = function(x){
                                if(x[["gene"]] %in% DC1_target$gene[DC1_target$label == "target_p"]) "DCtarget_p"
                                else if (x[["gene"]] %in% DC1_target$gene[DC1_target$label == "non-target"]) "non-target"
                                else "na"
                                  })
tmp_df[["Label"]] <- apply(tmp_df,1,
                              FUN = function(x){
                                if(x[["gene"]] %in% DC1_target$gene[DC1_target$label == "target"]) "DCtarget"
                                else if (x[["gene"]] %in% DC1_target$gene[DC1_target$label == "non-target"]) "non-target"
                                else "na"
                                  })
DC1_target <- tmp_df

library(readxl)
DC1_target <- read_excel("~/Desktop/At_Broad/Subcellular/04-22-22 YTHDC1 new label.xlsx")
tmp_df <- data.frame(gene = gene_list, Label_p = "na")
tmp_df[["Label_p"]] <- apply(tmp_df,1,
                              FUN = function(x){
                                if(x[["gene"]] %in% DC1_target$`DC1 target_p`) "DCtarget_p"
                                else if (x[["gene"]] %in% DC1_target$`DC1 non-target`) "non-target"
                                else "na"
                                  })
DC1_target <- tmp_df

tmp_df <- data.frame(group = c(rep("siControl",dim(res_list$siControl)[1]),
                               rep("siYTHDC1",dim(res_list$siYTHDC1)[1])), 
                     rbind(res_list$siControl[,c(-5,-10)],res_list$siYTHDC1[,c(-5,-10)])) %>%
  subset(subset = beta_r_sq >= 0.5)
  #subset(subset = beta_r_sq >= 0.5)

gene_list_overlap <- intersect(tmp_df$gene[tmp_df$group == "siControl"],tmp_df$gene[tmp_df$group == "siYTHDC1"])
#gene_list_overlap %<>%intersect(DC1_target$gene[DC1_target$target == "Yes"])
tmp_df %<>% subset(subset = gene %in% gene_list_overlap)
#tmp_df %<>% subset(subset = gene %in% DC1_target$gene[DC1_target$Label_p == "DCtarget_p"])

tmp_gene_list <- c("ITPRIP","TSC22D1","FBXO34","MCL1","PCBP1","TOR1AIP2","C15orf39","ASH1L","KLF4","OLFM1","FEM1B","IRF2BP2","LRFN4","CENPF","YTHDF1","CBX4","HNRNPA0","IRF2BP2","NFE2L1","MAML1","BCL2L1","LATS2","PPM1G","PPP1R15B","ZNF831","RPRD2","PM20D2","TMX1","TIA1","LAMB2","LYPLA2","APLP1","RAB13","LRP1","TOP2B","HEXA","CDCA7","WDR90","NUP155")

plot_list <- list()
tmp_vec <- c("alpha","beta","nc_slope")
#tmp_vec <- c("alpha","beta")
#Raw value comparison
for(i in tmp_vec){
  tmp_obj <- wilcox.test(x= tmp_df[[i]][tmp_df$group == 'siYTHDC1'], y = tmp_df[[i]][tmp_df$group == 'siControl'],
                        alternative = ifelse(i %in% c("alpha","beta","nc_slope"),"greater","less"),paired = T)

  plot_list[[i]] <- ggplot(tmp_df, aes_string(x = i, color = "group")) + 
    geom_step(aes(y=..y..),stat="ecdf") +labs(title = paste(i,"p:",format(tmp_obj$p.value, digits=3))) + 
    xlim(quantile(tmp_df[[i]],probs = c(0.01,0.99))) +
    theme_classic()
}

ggarrange(plotlist = plot_list,ncol = ceiling(length(tmp_vec)), nrow = 1)
##LogFC Comparison
tmp_vec <- c("alpha","beta","nc_slope")
tmp_df %<>% left_join(DC1_target,by = "gene")
tmp_df %<>% left_join(TEMPO_regression,by = "gene")
colnames(tmp_df)[which(colnames(tmp_df)=="slope")] <- "gamma"
tmp_df2 <- data.frame(gene = rep(tmp_df$gene,length(tmp_vec)),
                      Label = rep(tmp_df$Label_p,length(tmp_vec)), ctrl = 0, DC = 0, logFC = 0, 
                      para = rep(tmp_vec,each = length(gene_list_overlap)))
tmp_df2$ctrl <- apply(tmp_df2,1,
                      FUN = function(x){
                        tmp_df[[x[["para"]]]][tmp_df$group == "siControl" & tmp_df$gene == x[["gene"]]]
                      })
tmp_df2$DC <- apply(tmp_df2,1,
                      FUN = function(x){
                        tmp_df[[x[["para"]]]][tmp_df$group == "siYTHDC1" & tmp_df$gene == x[["gene"]]]
                      })
tmp_df2$logFC <- log2(tmp_df2$DC/tmp_df2$ctrl)
tmp_df2 %<>% subset(!is.na(logFC))

tmp_df2$logFC[tmp_df2$para == "gamma"] <- tmp_df2$ctrl[tmp_df2$para == "gamma"]

ggplot(data = tmp_df2 %>% subset(subset = Label == "DCtarget_p"),
       aes(x = para, y = logFC,fill = para)) +
  geom_violin(alpha = 0.5) +
  geom_boxplot(width=0.1, fill = "white") + 
  ylim(quantile(tmp_df2$logFC,probs = c(0.01,0.99))) +
  geom_hline(yintercept = 0, color = "red") +  theme_classic()

##logFC

plot_list <- list()
for(i in tmp_vec){
  tmp_obj <- wilcox.test(x = tmp_df2$logFC[tmp_df2$para == i & tmp_df2$Label == "DCtarget_p"], 
                         y = tmp_df2$logFC[tmp_df2$para == i & tmp_df2$Label == "non-target"],
                          alternative = ifelse(i %in% c("alpha","lambda"),"less","greater"))
  j <- quantile(tmp_df2$logFC[tmp_df2$para == i & tmp_df2$Label %in% c("DCtarget_p","non-target")],probs = c(0.01,0.99)) %>%
    abs() %>% mean()
  plot_list[[i]] <- ggplot(tmp_df2 %>% subset(subset = para == i & Label %in% c("DCtarget_p","non-target")),
                           aes_string(x = "logFC", color = "Label")) + 
    geom_step(aes(y=..y..),stat="ecdf") +labs(title = paste(i,"p:",format(tmp_obj$p.value, digits=3))) + 
    xlim(-j,j) +
    theme_classic()
}


ggarrange(plotlist = plot_list,ncol = ceiling(length(plot_list)/2), nrow = 2)

pdf("Feb01_para_curve.pdf", useDingbats = F, width = 8, height = 6)
plot_list %>% print()
dev.off()

####with 6 samples and no volume normalization
tmp_df <- data.frame(gene = rep(gene_list,5), 
                     sample = rep(c("1h_labeling", "1h_labeling_1h_wash", "1h_labeling_2h_wash", "1h_labeling_4h_wash", "1h_labeling_6h_wash"),
                                  each = length(gene_list)))
tmp_df %<>% left_join(DC1_target,by = "gene")
#nc_ratio cumulative curve
tmp_df[["dc"]] <- apply(tmp_df,1,
                              FUN = function(x){
                                tmp_vec <- starmap_normalized@meta.data$sample == x[["sample"]] & 
                                  starmap_normalized@meta.data$KD_label_new == "siYTHDC1"
                                DC   <- mean(starmap_raw_norm@assays$nucleus@data[x[["gene"]],tmp_vec])/mean(starmap_raw_norm@assays$cytoplasm@data[x[["gene"]],tmp_vec])
                                return(DC)
                              })
tmp_df[["ctrl"]] <- apply(tmp_df,1,
                              FUN = function(x){
                                tmp_vec <- starmap_normalized@meta.data$sample == x[["sample"]] & 
                                  starmap_normalized@meta.data$KD_label_new == "siControl"
                                ctrl <- mean(starmap_raw_norm@assays$nucleus@data[x[["gene"]],tmp_vec])/mean(starmap_raw_norm@assays$cytoplasm@data[x[["gene"]],tmp_vec])
                                return(ctrl)
                              })
tmp_df[["dc_vs_ctrl"]] <- apply(tmp_df,1,
                              FUN = function(x){
                                return(log2(as.numeric(x[["dc"]])/as.numeric(x[["ctrl"]])))
                              })
tmp_df %<>% subset(subset = gene %in% gene_list)

plot_list <- list()
for(i in levels(tmp_df$sample)){
  tmp_obj <- wilcox.test(x = tmp_df$dc_vs_ctrl[tmp_df$sample == i & tmp_df$gene %in% DC1_target$gene[DC1_target$Label_p == "DCtarget_p"]], 
                         y = tmp_df$dc_vs_ctrl[tmp_df$sample == i & tmp_df$gene %in% DC1_target$gene[DC1_target$Label_p == "non-target"]], 
                         paired = F,alternative = "greater")
  plot_list[[i]] <- ggplot(tmp_df %>% subset(subset = sample == i & Label_p != "na"), aes(x=dc_vs_ctrl, color=Label_p)) + 
    geom_step(aes(y=..y..),stat="ecdf") +labs(title = paste(i,"p:",format(tmp_obj$p.value, digits=3))) + xlim(-0.5,0.5) +
    theme_classic()
}

ggarrange(plotlist = plot_list,ncol = ceiling(length(levels(tmp_df$sample))/2), nrow = 2)
pdf("Jan29_nc_ratio_curve.pdf", useDingbats = F, width = 8, height = 6)
plot_list %>% print()
dev.off()

```


##Gene Cor.

```{r}
#####Subcellular Gene Correlation#####
plot_list <- list()
#Using cat nucleus and cyto matrix
tmp_df <- data.frame(gene = row.names(starmap_raw_norm@assays$RNA@counts[-c(1:7),]), 
                     cbind(starmap_raw_norm@assays$nucleus@data[-c(1:7),],starmap_raw_norm@assays$cytoplasm@data[-c(1:7),]))
#norm by total reads
tmp_df[,2:(dim(tmp_df)[2])] <- tmp_df[,2:(dim(tmp_df)[2])] / 
  matrix(rep(colSums(starmap_raw_norm@assays$RNA@counts[-c(1:7),]),2 * dim(tmp_df)[1] ),nrow = dim(tmp_df)[1], byrow = T) * 1000

tmp_df2 <- cor(t(as.matrix(tmp_df[,2:(dim(tmp_df)[2])])), method = "pearson",use = "complete.obs")


col_fun <- colorRamp2(seq(min(-0.2), max(0.2), length = 100), colorRampPalette(rev(brewer.pal(n = 5, name = "Spectral")))(100))

colnames(tmp_df2) <- row.names(tmp_df2) <- tmp_df$gene
plot_list[["combined"]] <- 
    Heatmap(tmp_df2, use_raster = T, raster_quality = 5, col = col_fun,
            right_annotation = rowAnnotation(cluster = as.character(tmp_df$cluster), 
                                             col = list(cluster = c("0" = "#F0AF00", "1" = "#153EF5", "2" = "#0BF53A", "3" = "#F50206"))), 
            show_row_names = F,  show_column_names = F, row_dend_reorder = F, column_dend_reorder = F)
tmp_vec <- column_order(plot_list[["combined"]])
#write.csv(tmp_df2[tmp_vec,tmp_vec],"mat_combined2.csv",row.names = F)

#gene cl result
gene_cl_res <- data.frame(gene = tmp_df$gene, 
                          cluster = 0)
gene_cl_res$cluster <- apply(gene_cl_res,1,
                             FUN = function(x){
                               ind <- which(tmp_vec == which(tmp_df$gene == x[["gene"]]))
                               if(ind <= 322) 1
                               else if(ind <= 473) 2
                               else if(ind <= 919) 3
                               else 4
                             })

for(i in c("1h_labeling","1h_labeling_2h_wash","1h_labeling_4h_wash","1h_labeling_6h_wash")){
    tmp_df2 <- tmp_df[,2:(dim(tmp_df)[2])] %>% .[,starmap_normalized@meta.data$sample == i] %>%
        as.matrix() %>% t() %>% cor(method = "pearson", use = "complete.obs")
    colnames(tmp_df2) <- row.names(tmp_df2) <- tmp_df$gene
    #write.csv(tmp_df2[tmp_vec,tmp_vec],paste0("mat_",i,".csv"),row.names = F)
    plot_list[[i]] <- 
        Heatmap(tmp_df2, use_raster = T, raster_quality = 5, col = col_fun,
                show_row_names = F,  show_column_names = F, column_order = tmp_vec, row_order = tmp_vec)
}

draw(plot_list[[2]]+plot_list[[3]]+plot_list[[4]]+plot_list[[5]]+plot_list[[1]])



pdf("Mar29_group4_ht_list.pdf",width = 30,height = 6)
draw(plot_list[[2]]+plot_list[[3]]+plot_list[[4]]+plot_list[[5]]+plot_list[[1]])
dev.off()



```

### Cluster boxplot

```{r }
#Cor cluster
res_df <- left_join(cl_res_list$sder_cc,res_list$siControl,by = "gene")
res_df <- left_join(res_df,TEMPO_regression,by = "gene")
res_df$cluster <- as.factor(res_df$cluster)
colnames(res_df)[which(colnames(res_df) == "slope")] <- "gamma"
plot_list <- list()
for(i in c("alpha","beta","gamma","nc_slope")){
  tmp_obj <- aov(res_df[["alpha"]]~res_df[["cluster"]]) %>% summary()
  plot_list[[i]] <- ggplot(res_df,aes_string(x = "cluster", y = i, fill = "cluster"))+
    geom_boxplot(width=0.7, notch = TRUE, alpha = 0.5) + 
    ylim(quantile(res_df[[i]], probs = c(0,0.99))) + 
    #geom_boxplot(width = 0.1, fill = "white") + 
    theme_classic() +
    labs(title = paste(i,"ANOVA Pr:",tmp_obj[[1]][["Pr(>F)"]][1]))
}

ggarrange(plotlist = plot_list,nrow = 2,ncol = 2)
```

## Gene Clustering 
### Cl Func Def
```{r}
##Function Defination
#Get Standard data
get_para_df <- function(g,tmp_list = res_list){
  g_G1 <- paste0(g,"_G1")
  g_S <- paste0(g,"_S")
  g_G2M <- paste0(g,"_G2M")
  gene_list_overlap <- intersect(intersect(res_list[[g_G1]]$gene,res_list[[g_S]]$gene),res_list[[g_G2M]]$gene)
  tmp_df <- data.frame(gene = gene_list_overlap,
                       G1_alpha = 0, S_alpha = 0, G2M_alpha = 0,
                       G1_beta = 0,S_beta = 0,G2M_beta = 0,
                       G1_beta_rsq = 0, S_beta_rsq = 0, G2M_beta_rsq = 0,
                       G1_nc = 0, S_nc = 0, G2M_nc = 0)
  
  tmp_df$G1_alpha <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_G1]]$alpha[tmp_list[[g_G1]]$gene == x[["gene"]] ]})
  tmp_df$G1_beta <-  apply(tmp_df,1,FUN = function(x){tmp_list[[g_G1]]$beta[tmp_list[[g_G1]]$gene == x[["gene"]] ]})
  tmp_df$S_alpha <-  apply(tmp_df,1,FUN = function(x){tmp_list[[g_S]]$alpha[tmp_list[[g_S]]$gene == x[["gene"]] ]})
  tmp_df$S_beta <-   apply(tmp_df,1,FUN = function(x){tmp_list[[g_S]]$beta[tmp_list[[g_S]]$gene == x[["gene"]] ]})
  tmp_df$G2M_alpha <-apply(tmp_df,1,FUN = function(x){tmp_list[[g_G2M]]$alpha[tmp_list[[g_G2M]]$gene == x[["gene"]] ]})
  tmp_df$G2M_beta <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_G2M]]$beta[tmp_list[[g_G2M]]$gene == x[["gene"]] ]})
  
  tmp_df$G1_beta_rsq <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_G1]]$beta_r_sq[tmp_list[[g_G1]]$gene == x[["gene"]] ]})
  tmp_df$S_beta_rsq <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_S]]$beta_r_sq[tmp_list[[g_S]]$gene == x[["gene"]] ]})
  tmp_df$G2M_beta_rsq <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_G2M]]$beta_r_sq[tmp_list[[g_G2M]]$gene == x[["gene"]] ]})
  
  tmp_df$G1_nc <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_G1]]$nc_slope[tmp_list[[g_G1]]$gene == x[["gene"]] ]})
  tmp_df$S_nc <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_S]]$nc_slope[tmp_list[[g_S]]$gene == x[["gene"]] ]})
  tmp_df$G2M_nc <- apply(tmp_df,1,FUN = function(x){tmp_list[[g_G2M]]$nc_slope[tmp_list[[g_G2M]]$gene == x[["gene"]] ]})
  

  return(tmp_df)
}

##END of Func Def.
```

### Kmeans Cl

```{r}
#Filter by r^2 > 0.5
para_df <- get_para_df("siControl")
tmp_df <- para_df %>% subset(subset = G1_beta_rsq >= 0.5 & S_beta_rsq >= 0.5 & G2M_beta_rsq >= 0.5)
TEMPO_regression_cc <- read_csv("~/Desktop/At_Broad/Subcellular/TEMPO-regression_cc_siControl_new.csv")
tmp_df <- left_join(tmp_df,TEMPO_regression_cc[,c(2,3,5,7)])
#tmp_df[,c(2:7)] <- t(scale(t(as.matrix(tmp_df[,c(2:7)]))))

tmp_df[,c(2:4)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#a
tmp_df[,c(5:7)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#beta
tmp_df[,c(11:13)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#nc
tmp_df[,c(14:16)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#gamma
#create list for saving clustering results
cl_res_list <- list()

#kmeans try
library(factoextra)
library(ComplexHeatmap)
fviz_nbclust(tmp_df[,c(2:7,11:16)],kmeans,k.max = 15,method = "wss")
set.seed(2021)
tmp_df.km_res <- kmeans(tmp_df[,c(2:7,11:13)],5,nstart = 25)
#PC
fviz_cluster(tmp_df.km_res,as.matrix(tmp_df[,c(2:7,11:13)]),axes = c(1,2), 
             labelsize = 0, ellipse = F, show.clust.cent = F, shape = 16) + 
  theme_classic()

ggplot(data = data.frame(cluster = as.factor(tmp_df.km_res$cluster),tmp_df),
       aes(x = G1_beta,y = G2M_beta,color = cluster))+
  geom_point(alpha = 0.5) + 
  theme_classic()
#save result
cl_res_list[["sd_cc"]] <- data.frame(para_df %>% 
                                       subset(subset = G1_beta_rsq >= 0.5 & S_beta_rsq >= 0.5 & G2M_beta_rsq >= 0.5),
                                     cluster = tmp_df.km_res$cluster)

#Check Highest Expr
plot_list <- list()
for(k in 1:4){
  plot_list[[i]] <- Heatmap(tmp_df[tmp_df.km_res$cluster == k, 2:7],
                            cluster_columns = F,cluster_rows  = T, show_row_names = F,
                            column_title = paste("Cluster",k)) 
  print(which(colSums(tmp_df[tmp_df.km_res$cluster == k, 2:7]) == 
                max(colSums(tmp_df[tmp_df.km_res$cluster == k, 2:7]))))
}
```

### Seurat Clustering

```{r Clustering Using Lambda etc.}
#Filter by r^2 > 0.5
para_df <- get_para_df("siControl")
tmp_df <- para_df %>% subset(subset = G1_beta_rsq >= 0.5 & S_beta_rsq >= 0.5 & G2M_beta_rsq >= 0.5) #%>%

#tmp_df[,c(11:13)] <- tmp_df[,c(11:13)] * -1

tmp_df[,c(2:4)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#a
tmp_df[,c(5:7)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#beta
tmp_df[,c(11:13)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#nc

#Add Connie Regression Result
tmp_df %<>% left_join(TEMPO_regression_cc[,c(2,3,5,7)], by = "gene")
tmp_df[, c(14:16)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#regression
#Using K-means
fviz_nbclust(tmp_df[,c(2:7,11:16)],kmeans,k.max = 15,method = "wss")
set.seed(2021)
tmp_df.km_res <- kmeans(tmp_df[,c(2:7,11:16)],4,nstart = 25)
#PC
fviz_cluster(tmp_df.km_res,as.matrix(tmp_df[,c(2:7,11:16)]),axes = c(1,2), 
             labelsize = 0, ellipse = F, show.clust.cent = F, shape = 16) + 
  theme_classic()

cl_res_list[["sder_cc_km"]] <- right_join(by = "gene", para_df, TEMPO_regression_cc) %>%
  right_join(data.frame(gene = tmp_df$gene,
                        cluster = tmp_df.km_res$cluster), by = "gene")

#Try Seurat Clustering
#Using Regression Value
tmp_obj <- CreateSeuratObject(counts = as.data.frame(tmp_df[,c(2:7,11:16)], 
                                                     row.names = as.character(tmp_df$gene)) %>% as.matrix() %>% t(),
                              project = "Gene_clustering") %>% ScaleData(do.scale = F, do.center = F)

#tmp_obj %<>% AddMetaData(metadata = data.frame(row.names = tmp_df$gene, cluster_old = tmp_df$cluster))

tmp_obj %<>% RunPCA(features = row.names(tmp_obj@assays[["RNA"]]), npcs = 15)

ElbowPlot(tmp_obj)

tmp_obj %<>% FindNeighbors(dims = 1:10)
tmp_obj %<>% FindClusters(resolution = 1)

tmp_obj %<>% RunUMAP(dims = 1:10)

DimPlot(tmp_obj, reduction = "umap")
DoHeatmap(tmp_obj, features = row.names(tmp_obj@assays$RNA)) + NoLegend()

#export cluster Regression Value
cl_res_list[["sder_cc"]] <- right_join(by = "gene", para_df, TEMPO_regression_cc) %>%
  right_join(data.frame(gene = tmp_obj@assays[["RNA"]]@data@Dimnames[[2]],
                        cluster = tmp_obj@meta.data[["seurat_clusters"]]), by = "gene")


tmp_df2 <- data.frame(old_cluster = tmp_obj@meta.data$cluster_old, cluster_0.8 = tmp_obj@meta.data$RNA_snn_res.0.8) %>% 
  dplyr::count(old_cluster,cluster_0.8,sort = F)

ggplot(data = tmp_df2, aes(x = old_cluster, y = cluster_0.8, fill = n)) + 
  geom_tile() + 
  scale_fill_gradient(low="white", high="blue") +
  theme_classic()

tmp_df <- cl_res_list$sder_cc[,c(1,2:4,5:7,11:13,15,17,19,21)]

tmp_df[,c(2:4)]   %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#a
tmp_df[,c(5:7)]   %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#beta
tmp_df[,c(8:10)]  %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#nc
tmp_df[,c(11:13)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#gamma

require(circlize)
col_fun <- colorRamp2(quantile(unlist(tmp_df[,2:13]),probs = c(0.1,0.5,0.9)), c("#0000FF", "#FFFFFF", "#FF0000"))

Heatmap(matrix = tmp_df[,2:13], cluster_columns = F,cluster_rows  = F, show_row_names = F, col = col_fun,
        column_order = colnames(tmp_df)[2:13],row_split = as.factor(tmp_df$cluster), 
        column_split = factor(rep(c("alpha","beta","nc_slope","gamma"),each = 3),
                              levels = c("alpha","beta","nc_slope","gamma")))


```

```{r using KD/Ctrl}
#Add Connie Regression Result
require(readr)
TEMPO_regression_cc <- read_csv("~/Desktop/At_Broad/Subcellular/TEMPO-regression_cc_siControl_new.csv")
TEMPO_regression_cc_DC <- read_csv("~/Desktop/At_Broad/Subcellular/TEMPO-regression_cc_siYTHDC1_new.csv")

para_df <- left_join(get_para_df("siControl"),get_para_df("siYTHDC1"),by="gene",suffix = c(".C",".DC")) 
tmp_df <- para_df %>% subset(subset = G1_beta_rsq.C >= 0.5 & S_beta_rsq.C >= 0.5 & G2M_beta_rsq.C >= 0.5 & G1_beta_rsq.DC >= 0.5 & S_beta_rsq.DC >= 0.5 & G2M_beta_rsq.DC >= 0.5) 

tmp_df %<>% left_join(TEMPO_regression_cc[,c(2,3,5,7)], by = "gene")
colnames(tmp_df)[26:28] <- c("G1_slope.C","S_slope.C","G2M_slope.C")
tmp_df %<>% left_join(TEMPO_regression_cc_DC[,c(2,3,5,7)], by = "gene")
colnames(tmp_df)[29:31] <- c("G1_slope.DC","S_slope.DC","G2M_slope.DC")
#remove beta_rsq
tmp_df <- tmp_df[-c(8:10,20:22)]
tmp_df2 <- tmp_df

tmp_df[,c(2:4, 11:13)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#a
tmp_df[,c(5:7, 14:16)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#beta
tmp_df[,c(8:10,17:19)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#nc
tmp_df[, c(20:25)] %<>% unlist() %>%  scale() %>% matrix(ncol = 3)#regression



#Try Seurat Clustering
#Using Regression Value
tmp_obj <- CreateSeuratObject(counts = as.data.frame(tmp_df[,c(2:25)], 
                                                     row.names = as.character(tmp_df$gene)) %>% as.matrix() %>% t(),
                              project = "Gene_clustering") %>% ScaleData(do.scale = F, do.center = F)

#tmp_obj %<>% AddMetaData(metadata = data.frame(row.names = tmp_df$gene, cluster_old = tmp_df$cluster))

tmp_obj %<>% RunPCA(features = row.names(tmp_obj@assays[["RNA"]]), npcs = 15)

ElbowPlot(tmp_obj)

tmp_obj %<>% FindNeighbors(dims = 1:14)
tmp_obj %<>% FindClusters(resolution = 0.8)

tmp_obj %<>% RunUMAP(dims = 1:10)

DimPlot(tmp_obj, reduction = "umap")
DoHeatmap(tmp_obj, features = row.names(tmp_obj@assays$RNA)) + NoLegend()

#export cluster Regression Value
cl_res_list[["sder_cc_dc"]] <- tmp_df %>%
  right_join(data.frame(gene = tmp_obj@assays[["RNA"]]@data@Dimnames[[2]],
                        cluster = tmp_obj@meta.data[["seurat_clusters"]]), by = "gene")

tmp_df <- cl_res_list$sder_cc_dc

col_fun <- colorRamp2(quantile(unlist(tmp_df[,2:25]),probs = c(0.1,0.5,0.9)), c("#0000FF", "#FFFFFF", "#FF0000"))

tmp_df2 <- tmp_df[,c(1,2:4,11:13,5:7,14:16,8:10,17:19,20:25,26)]

Heatmap(matrix = tmp_df2[,2:25], cluster_columns = F,cluster_rows  = F, show_row_names = F, col = col_fun,
        row_split = as.factor(tmp_df2$cluster), 
        column_split = factor(rep(c("alpha","beta","nc_slope","gamma"),each = 6),
                              levels = c("alpha","beta","nc_slope","gamma")))

```

### Confusion Mat.

```{r }
tmp_df2 <- left_join(cl_res_list$sder_cc_dc,cl_res_list$sder_cc, by = "gene", suffix = c(".dc",".c")) %>%
  group_by(cluster.dc, cluster.c) %>% summarise(value = n())

ggplot(data = tmp_df2, aes(x = cluster.c, y = cluster.dc, fill = value)) + 
  geom_tile() + 
  geom_text(aes(label = value)) + 
  scale_fill_gradient(low="white", high="blue") +
  theme_classic()

tmp_df2 <- left_join(cl_res_list$sder_cc,cl_res_list$sder_cc_km, by = "gene", suffix = c(".c",".km")) %>%
  group_by(cluster.c, cluster.km) %>% summarise(value = n())

ggplot(data = tmp_df2, aes(x = cluster.c, y = cluster.km, fill = value)) + 
  geom_tile() + 
  geom_text(aes(label = value)) + 
  scale_fill_gradient(low="white", high="blue") +
  theme_classic()

tmp_df2 <- left_join(cl_res_list$sder_cc,gene_cl_res, by = "gene", suffix = c(".para",".cor")) %>%
  group_by(cluster.para, cluster.cor) %>% summarise(value = n())

ggplot(data = tmp_df2, aes(x = cluster.para, y = cluster.cor, fill = value)) + 
  geom_tile() + 
  geom_text(aes(label = value)) + 
  scale_fill_gradient(low="white", high="blue") +
  theme_classic()

```

## Figures

### m6A Boxplot

```{r}
#m6A Label
m6A_label <- read_csv("~/Desktop/At_Broad/Subcellular/m6A_new_label.csv") %>% .[,1:3]
m6A_label[["Label"]] <- apply(m6A_label,1,
                              FUN = function(x){
                                if(x[["m6A"]] == "Y") "m6A"
                                else if(x[["non-m6A"]] == "Y") "non_m6A"
                                else "na"
                                  })



tmp_df <- get_para_df("siControl")
tmp_df %<>% subset(subset = G1_beta_rsq >= 0.5 & S_beta_rsq >= 0.5 & G2M_beta_rsq >= 0.5)
tmp_df %<>% left_join(m6A_label, by = c("gene" = "Gene")) %>% left_join(TEMPO_regression_cc,by = "gene") 

colnames(tmp_df)[c(18,20,22)] <- c("G1_gamma","S_gamma","G2M_gamma")

library(ggsignif)

plot_list <- list()
for(i in c("alpha","beta","nc","gamma")){
  tmp_vec <- quantile(tmp_df[,paste0(c("G1","S","G2M"),"_",i)] %>% unlist(), probs = c(0.01,0.75,0.99))
  for(j in c("G1","S","G2M")){
    tmp_obj <- wilcox.test(x = tmp_df[,paste0(j,"_",i)][tmp_df$Label == "m6A"],
                           y = tmp_df[,paste0(j,"_",i)][tmp_df$Label == "non_m6A"])
    plot_list[[paste0(j,"_",i)]] <- ggplot(data = data.frame(value = tmp_df[,paste0(j,"_",i)],
                                                             group = tmp_df$Label) %>% subset(subset = group != "na"),
                                           aes(x = group, y = value, fill = group)) + 
      geom_boxplot(width=0.7, notch = TRUE, alpha = 0.5) + 
      #geom_signif(comparisons = list(c("m6A", "non_m6A")), 
      #        map_signif_level = T, y_position = tmp_vec[2], tip_length = 0, vjust=0.4) + 
      ylim(tmp_vec[c(1,3)]) + 
      theme_classic() + labs(title = paste0(j,"_",i)) + 
      xlab(paste0("pval ",tmp_obj$p.value %>% formatC(format = "e", digits = 1))) +
      theme(legend.position = "none") +
      scale_fill_manual(values = c("#7CAE02","#F8766D"))
      
  }
}

ggarrange(plotlist = plot_list,ncol = 3, nrow = 4)


tmp_df <- res_list$siControl[,c(1,6,2,3,21)]
tmp_df %<>% subset(subset = beta_r_sq >= 0.5)
tmp_df %<>% left_join(m6A_label, by = c("gene" = "Gene")) %>% left_join(TEMPO_regression[,c(2,3)],by = "gene") 

colnames(tmp_df)[c(9)] <- c("gamma")

library(ggsignif)

plot_list <- list()
for(i in c("alpha","beta","nc_slope","gamma")){
    tmp_obj <- wilcox.test(x = tmp_df[,paste0(i)][tmp_df$Label == "m6A"],
                           y = tmp_df[,paste0(i)][tmp_df$Label == "non_m6A"])
    plot_list[[paste0(i)]] <- ggplot(data = data.frame(value = tmp_df[,paste0(i)],
                                                             group = tmp_df$Label) %>% subset(subset = group != "na"),
                                           aes(x = group, y = value, fill = group)) + 
      geom_boxplot(width=0.7, notch = TRUE, alpha = 0.5) + 
      theme_classic() + labs(title = paste0(i)) + 
      xlab(paste0("pval ",tmp_obj$p.value %>% formatC(format = "e", digits = 1))) +
      theme(legend.position = "none") +
      scale_fill_manual(values = c("#7CAE02","#F8766D"))
}

ggarrange(plotlist = plot_list,ncol = 2, nrow = 2)


```

### nc_ratio comparison 

```{r }

tmp_df <- data.frame(gene = gene_list)

for(j in levels(starmap_raw_norm@meta.data$sample)){
  for(k in c("siControl","siYTHDC1")){
      tmp_vec <- starmap_raw_norm@meta.data$sample == j & 
        starmap_raw_norm@meta.data$KD_label_new == k
      tmp_df[[paste0(j,"_",k,"_nc")]] <- apply(tmp_df,1,
                                         FUN = function(x){
                                           sum(starmap_raw_norm@assays$nucleus@data[x[["gene"]], tmp_vec]) /
                                              sum(starmap_raw_norm@assays$cytoplasm@data[x[["gene"]], tmp_vec])
                                         })
      }
  tmp_df[[paste0("logfc_",j)]] <- log2(tmp_df[[paste0(j,"_","siYTHDC1","_nc")]]/tmp_df[[paste0(j,"_","siControl","_nc")]])
}


tmp_df <- left_join(tmp_df,DC1_target,by = "gene")

plot_list <- list()
for(i in levels(starmap_raw_norm@meta.data$sample)){
  tmp_obj <- wilcox.test(x = tmp_df[[paste0("logfc_",i)]][tmp_df$Label_p == "DCtarget_p"], 
                         y = tmp_df[[paste0("logfc_",i)]][tmp_df$Label_p == "non-target"],
                          alternative = "greater")
  j <- quantile(tmp_df[[paste0("logfc_",i)]][tmp_df$Label_p %in% c("DCtarget_p","non-target")],probs = c(0.01,0.99)) %>%
    abs() %>% mean()
  plot_list[[i]] <- ggplot(tmp_df %>% subset(subset = Label_p %in% c("DCtarget_p","non-target")),
                           aes_string(x = paste0("logfc_",i), color = "Label_p")) + 
    geom_step(aes(y=..y..),stat="ecdf") +labs(title = paste(i,"p:",format(tmp_obj$p.value, digits=3))) + 
    xlim(-j,j) +
    theme_classic()
}

ggarrange(plotlist = plot_list,ncol = 3, nrow = 2)



```



